name: Download workflow artifact
description: Download and extract an artifact associated with given workflow and commit
author: dawidd6
branding:
  icon: download
  color: blue
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  workflow:
    description: Workflow name
    required: true
  repo:
    description: Repository name with owner (like actions/checkout)
    required: false
    default: ${{github.repository}}
  pr:
    description: Pull request number
    required: false
  commit:
    description: Commit SHA1
    required: false
  name:
    description: Artifact name
    required: true
  path:
    description: Where to unpack the artifact
    required: false
    default: "./"
  branch:
    description: Branch
    required: false
runs:
  using: node12
  main: main.js
