name: Upload

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: upload

permissions: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact artifact1 artifact2
          printf '%s\n' "$GITHUB_SHA" | tee raw-artifact artifact/sha artifact1/sha1 artifact2/sha2 > /dev/null
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: artifact
      - name: Upload raw
        uses: actions/upload-artifact@v7
        with:
          path: raw-artifact
          archive: false
      - name: Upload first
        uses: actions/upload-artifact@v7
        with:
          name: artifact1
          path: artifact1
      - name: Upload second
        uses: actions/upload-artifact@v7
        with:
          name: artifact2
          path: artifact2
